name: release
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message,'build:')"
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'mandrel'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: "maven"

      - name: build release
        run: |
          ./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true


      - name: "Get the tag"
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}


      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${{ steps.get_tag.outputs.tag }}
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

          gh release create "$tag" \
          --title="$tag" \
          --draft \
          soulstone-backend-$version-runner
          
        
          
          
